---
# local
proj_env: local
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "[%(asctime)s][%(levelname)7s][%(name)s]-> %(message)s"
    datefmt: '%H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
root:
  level: DEBUG
  handlers: [ console ]
---
# prod
proj_env: prod
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "[%(asctime)s][%(levelname)7s][%(name)s]-> %(message)s"
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: 'logs/info.log'
    mode: 'a+'
    maxBytes: 67108864
    backupCount: 4
    encoding: utf8
  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: 'logs/error.log'
    mode: 'a+'
    maxBytes: 67108864
    backupCount: 2
    encoding: utf8
root:
  level: INFO
  handlers: [ info_file_handler,error_file_handler ]
loggers:
  my_module:
    level: ERROR
    handlers: [ info_file_handler ]
    propagate: no
